def erro():
    try:
        int("a")
    except Exception as e:
        print (e)


erro()
